name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base_indepth: yes
          plugin_languages: yes
          plugin_traffic: yes
          plugin_lines: yes
          plugin_lines_sections: base
          plugin_languages_indepth: yes
          plugin_languages_details: lines
          plugin_lines_repositories_limit: 100
          repositories_skipped: dstreetfinance/release
          
